CREATE DATABASE IF NOT EXISTS `catalog`;

CREATE TABLE IF NOT EXISTS `catalog`.`categories` (
`id` INT UNSIGNED NOT NULL,
`name` VARCHAR(250) NOT NULL ,
PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `catalog`.`brands` (
`id` INT UNSIGNED NOT NULL,
`name` VARCHAR(200),
`category` INT,
PRIMARY KEY(`id`),
CONSTRAINT `category` FOREIGN KEY(`category`) REFERENCES `catalog`.`categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `catalog`.`products` (
`id` INT,
`title` VARCHAR(100),
`description` VARCHAR(250),
`price` INT,
`discount` INT,
`rating` INT,
`stock` INT,
`imageurl` VARCHAR(250),
`brand_id` INT,
`category_id` INT,
PRIMARY KEY(`id`) ,
INDEX `CATEGORY_ID`(`category_id` ASC) ,
INDEX `BRAND_ID`(`brand_id` ASC) ,
CONSTRAINT `brand_id` FOREIGN KEY(`brand_id`) REFERENCES `catalog`.`brands`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE ,
CONSTRAINT `category_id` FOREIGN KEY(`category_id`) REFERENCES `catalog`.`categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `catalog`.`images` (
`id` INT UNSIGNED NOT NULL,
`image1` TEXT,
`image2` TEXT,
`image3` TEXT,
`image4` TEXT,
`image5` TEXT,
`image6` TEXT,
PRIMARY KEY(`id`) ,
CONSTRAINT `id` FOREIGN KEY(`id`) REFERENCES `catalog`.`products`(`id`)
);

use catalog;

INSERT INTO categories VALUES
(1,'smartphones'),
(2,'laptops'),
(3,'fragrances'),
(4,'skincare'),
(5,'groceries'),
(6,'home-decoration'),
(7,'furniture'),
(8,'tops'),
(9,'womens-dresses'),
(10,'womens-shoes'),
(11,'mens-shirts'),
(12,'mens-shoes'),
(13,'mens-watches'),
(14,'womens-watches'),
(15,'womens-bags'),
(16,'womens-jewellery'),
(17,'sunglasses'),
(18,'automotive'),
(19,'motorcycle'),
(20,'lighting');

INSERT INTO brands VALUES
(1,'Apple',1),
(2,'Samsung',1),
(3,'OPPO',1),
(4,'Huawei',1),
(5,'APPle',2),
(6,'Microsoft Surface',2),
(7,'Infinix',2),
(8,'HP Pavilion',2),
(9,'Impression of Acqua Di Gio',3),
(10,'Royal_Mirage',3),
(11,'Fog Scent Xpressio',3),
(12,'Al Munakh',3),
(13,'Lord - Al-Rehab',3),
(14,'L''Oreal Paris',4),
(15,'Hemani Tea',4),
(16,'Dermive',4),
(17,'ROREC White Rice',4),
(18,'Fair & Clear',4),
(19,'Saaf & Khaas',5),
(20,'Bake Parlor Big',5),
(21,'Baking Food Items',5),
(22,'fauji',5),
(23,'Dry Rose',5),
(24,'Boho Decor',6),
(25,'Flying Wooden',6),
(26,'LED Lights',6),
(27,'luxury palace',6),
(28,'Golden',6),
(29,'Furniture Bed Set',7),
(30,'Ratttan Outdoor',7),
(31,'Kitchen Shelf',7),
(32,'Multi Purpose',7),
(33,'AmnaMart',7),
(34,'Professional Wear',8),
(35,'Soft Cotton',8),
(36,'Top Sweater',8),
(37,'RED MICKY MOUSE..',9),
(38,'Digital Printed',9),
(39,'Ghazi Fabric',9),
(40,'IELGY',9),
(41,'IELGY fashion',10),
(42,'Synthetic Leather',10),
(43,'Sandals Flip Flops',10),
(44,'Maasai Sandals',10),
(45,'Arrivals Genuine',10),
(46,'Vintage Apparel',11),
(47,'FREE FIRE',11),
(48,'The Warehouse',11),
(49,'Sneakers',12),
(50,'Rubber',12),
(51,'Naviforce',13),
(52,'SKMEI 9117',13),
(53,'Strap Skeleton',13),
(54,'Stainless',13),
(55,'Eastern Watches',14),
(56,'Luxury Digital',14),
(57,'Watch Pearls',14),
(58,'Bracelet',14),
(59,'LouisWill',15),
(60,'Copenhagen Luxe',15),
(61,'Steal Frame',15),
(62,'Darojay',16),
(63,'Fashion Jewellery',16),
(64,'Cuff Butterfly',16),
(65,'Designer Sun Glasses',17),
(66,'mastar watch',17),
(67,'Car Aux',18),
(68,'W1209 DC12V',18),
(69,'TC Reusable',18),
(70,'Neon LED Light',18),
(71,'METRO 70cc Motorcycle - MR70',19),
(72,'BRAVE BULL',19),
(73,'shock absorber',19),
(74,'JIEPOLLY',19),
(75,'Xiangle',19),
(76,'lightingbrilliance',20),
(77,'Ifei Home',20),
(78,'DADAWU',20),
(79,'YIOSI',20);

INSERT INTO products VALUES
(1,'iPhone 9','An apple mobile which is nothing like apple',549,13,5,94,'https://dummyjson.com/image/i/products/1/thumbnail.jpg',1,1),
(2,'iPhone X','SIM-Free\, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',899,18,4,34,'https://dummyjson.com/image/i/products/2/thumbnail.jpg',1,1),
(3,'Samsung Universe 9','Samsung''s new variant which goes beyond Galaxy to the Universe',1249,15,4,36,'https://dummyjson.com/image/i/products/3/thumbnail.jpg',2,1),
(4,'OPPOF19','OPPO F19 is officially announced on April 2021.',280,18,4,123,'https://dummyjson.com/image/i/products/4/thumbnail.jpg',3,1),
(5,'Huawei P30','Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',499,11,4,32,'https://dummyjson.com/image/i/products/5/thumbnail.jpg',4,1),
(6,'MacBook Pro','MacBook Pro 2021 with mini-LED display may launch between September\, November',1749,11,5,83,'https://dummyjson.com/image/i/products/6/thumbnail.png',5,2),
(7,'Samsung Galaxy Book','Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip\, 8GB of RAM Launched',1499,4,4,50,'https://dummyjson.com/image/i/products/7/thumbnail.jpg',2,2),
(8,'Microsoft Surface Laptop 4','Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',1499,10,4,68,'https://dummyjson.com/image/i/products/8/thumbnail.jpg',6,2),
(9,'Infinix INBOOK','Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty',1099,12,5,96,'https://dummyjson.com/image/i/products/9/thumbnail.jpg',7,2),
(10,'HP Pavilion 15-DK1056WM','HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5\, 8GB\, 256GB SSD\, GTX 1650 4GB\, Windows 10',1099,6,4,89,'https://dummyjson.com/image/i/products/10/thumbnail.jpeg',8,2),
(11,'perfume Oil','Mega Discount\, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil',13,8,4,65,'https://dummyjson.com/image/i/products/11/thumbnail.jpg',9,3),
(12,'Brown Perfume','Royal_Mirage Sport Brown Perfume for Men & Women - 120ml',40,16,4,52,'https://dummyjson.com/image/i/products/12/thumbnail.jpg',10,3),
(13,'Fog Scent Xpressio Perfume','Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men',13,8,5,61,'https://dummyjson.com/image/i/products/13/thumbnail.webp',11,3),
(14,'Non-Alcoholic Concentrated Perfume Oil','Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil',120,16,4,114,'https://dummyjson.com/image/i/products/14/thumbnail.jpg',12,3),
(15,'Eau De Perfume Spray','Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality',30,11,5,105,'https://dummyjson.com/image/i/products/15/thumbnail.jpg',13,3),
(16,'Hyaluronic Acid Serum','L''OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid',19,13,5,110,'https://dummyjson.com/image/i/products/16/thumbnail.jpg',14,4),
(17,'Tree Oil 30ml','Tea tree oil contains a number of compounds\, including terpinen-4-ol\, that have been shown to kill certain bacteria\,',12,4,5,78,'https://dummyjson.com/image/i/products/17/thumbnail.jpg',15,4),
(18,'Oil Free Moisturizer 100ml','Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides\, hyaluronic acid & sunscreen.',40,13,5,88,'https://dummyjson.com/image/i/products/18/thumbnail.jpg',16,4),
(19,'Skin Beauty Serum.','Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m',46,11,4,54,'https://dummyjson.com/image/i/products/19/thumbnail.jpg',17,4),
(20,'Freckle Treatment Cream- 15gm','Fair & Clear is Pakistan''s only pure Freckle cream which helpsfade Freckles\, Darkspots and pigments. Mercury level is 0%\, so there are no side effects.',70,17,4,140,'https://dummyjson.com/image/i/products/20/thumbnail.jpg',18,4),
(21,'- Daal Masoor 500 grams','Fine quality Branded Product Keep in a cool and dry place',20,5,4,133,'https://dummyjson.com/image/i/products/21/thumbnail.png',19,5),
(22,'Elbow Macaroni - 400 gm','Product details of Bake Parlor Big Elbow Macaroni - 400 gm',14,16,5,146,'https://dummyjson.com/image/i/products/22/thumbnail.jpg',20,5),
(23,'Orange Essence Food Flavou','Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item',14,8,5,26,'https://dummyjson.com/image/i/products/23/thumbnail.jpg',21,5),
(24,'cereals muesli fruit nuts','original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji',46,17,5,113,'https://dummyjson.com/image/i/products/24/thumbnail.jpg',22,5),
(25,'Gulab Powder 50 Gram','Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds',70,14,5,47,'https://dummyjson.com/image/i/products/25/thumbnail.jpg',23,5),
(26,'Plant Hanger For Home','Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf',41,18,4,131,'https://dummyjson.com/image/i/products/26/thumbnail.jpg',24,6),
(27,'Flying Wooden Bird','Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF\, Laminated 3.5mm',51,16,4,17,'https://dummyjson.com/image/i/products/27/thumbnail.webp',25,6),
(28,'3D Embellishment Art Lamp','3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)',20,16,5,54,'https://dummyjson.com/image/i/products/28/thumbnail.jpg',26,6),
(29,'Handcraft Chinese style','Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate',60,15,4,7,'https://dummyjson.com/image/i/products/29/thumbnail.webp',27,6),
(30,'Key Holder','Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality',30,3,5,54,'https://dummyjson.com/image/i/products/30/thumbnail.jpg',28,6),
(31,'Mornadi Velvet Bed','Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set',40,17,4,140,'https://dummyjson.com/image/i/products/31/thumbnail.jpg',29,7),
(32,'Sofa for Coffe Cafe','Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe',50,16,5,30,'https://dummyjson.com/image/i/products/32/thumbnail.jpg',30,7),
(33,'3 Tier Corner Shelves','3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf',700,17,4,106,'https://dummyjson.com/image/i/products/33/thumbnail.jpg',31,7),
(34,'Plastic Table','V﻿ery good quality plastic table for multi purpose now in reasonable price',50,4,4,136,'https://dummyjson.com/image/i/products/34/thumbnail.jpg',32,7),
(35,'3 DOOR PORTABLE','Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe',41,8,4,68,'https://dummyjson.com/image/i/products/35/thumbnail.jpg',33,7),
(36,'Sleeve Shirt Womens','Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized',90,11,4,39,'https://dummyjson.com/image/i/products/36/thumbnail.jpg',34,8),
(37,'ank Tops for Womens/Girls','PACK OF 3 CAMISOLES \,VERY COMFORTABLE SOFT COTTON STUFF\, COMFORTABLE IN ALL FOUR SEASONS',50,12,5,107,'https://dummyjson.com/image/i/products/37/thumbnail.jpg',35,8),
(38,'sublimation plain kids tank','sublimation plain kids tank tops wholesale',100,11,5,20,'https://dummyjson.com/image/i/products/38/thumbnail.jpg',35,8),
(39,'Women Sweaters Wool','2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women'' S Crop Top Sweater',600,17,5,55,'https://dummyjson.com/image/i/products/39/thumbnail.jpg',36,8),
(40,'women winter clothes','women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set',57,13,5,84,'https://dummyjson.com/image/i/products/40/thumbnail.jpg',36,8),
(41,'NIGHT SUIT','NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.',55,15,5,21,'https://dummyjson.com/image/i/products/41/thumbnail.webp',37,9),
(42,'Stiched Kurta plus trouser','FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN',80,15,4,148,'https://dummyjson.com/image/i/products/42/thumbnail.jpg',38,9),
(43,'frock gold printed','Ghazi fabric long frock gold printed ready to wear stitched collection (G992)',600,16,4,150,'https://dummyjson.com/image/i/products/43/thumbnail.jpg',39,9),
(44,'Ladies Multicolored Dress','This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.',79,17,4,2,'https://dummyjson.com/image/i/products/44/thumbnail.jpg',39,9),
(45,'Malai Maxi Dress','Ready to wear\, Unique design according to modern standard fashion\, Best fitting \,Imported stuff',50,5,5,96,'https://dummyjson.com/image/i/products/45/thumbnail.jpg',40,9),
(46,'women''s shoes','Close: Lace\, Style with bottom: Increased inside\, Sole Material: Rubber',40,17,4,72,'https://dummyjson.com/image/i/products/46/thumbnail.jpg',41,10),
(47,'Sneaker shoes','Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women',120,10,4,50,'https://dummyjson.com/image/i/products/47/thumbnail.jpeg',42,10),
(48,'Women Strip Heel','Features: Flip-flops\, Mid Heel\, Comfortable\, Striped Heel\, Antiskid\, Striped',40,11,4,25,'https://dummyjson.com/image/i/products/48/thumbnail.jpg',43,10),
(49,'Chappals & Shoe Ladies Metallic','Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals',23,3,5,107,'https://dummyjson.com/image/i/products/49/thumbnail.jpg',44,10),
(50,'Women Shoes','2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes',36,17,4,46,'https://dummyjson.com/image/i/products/50/thumbnail.jpg',45,10),
(51,'half sleeves T shirts','Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands',23,13,4,132,'https://dummyjson.com/image/i/products/51/thumbnail.jpg',46,11),
(52,'FREE FIRE T Shirt','quality and professional print - It doesn''t just look high quality\, it is high quality.',10,15,5,128,'https://dummyjson.com/image/i/products/52/thumbnail.jpg',47,11),
(53,'printed high quality T shirts','Brand: vintage Apparel \,Export quality',35,8,5,6,'https://dummyjson.com/image/i/products/53/thumbnail.jpg',46,11),
(54,'Pubg Printed Graphic T-Shirt','Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking',46,16,5,136,'https://dummyjson.com/image/i/products/54/thumbnail.jpg',48,11),
(55,'Money Heist Printed Summer T Shirts','Fabric Jercy\, Size: M & L Wear Stylish Dual Stiched',66,16,5,122,'https://dummyjson.com/image/i/products/55/thumbnail.jpg',48,11),
(56,'Sneakers Joggers Shoes','Gender: Men \, Colors: Same as DisplayedCondition: 100% Brand New',40,13,4,6,'https://dummyjson.com/image/i/products/56/thumbnail.jpg',49,12),
(57,'Loafers for men','Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.',47,11,5,20,'https://dummyjson.com/image/i/products/57/thumbnail.jpg',50,12),
(58,'formal offices shoes','Pattern Type: Solid\, Material: PU\, Toe Shape: Pointed Toe \,Outsole Material: Rubber',57,12,4,68,'https://dummyjson.com/image/i/products/58/thumbnail.jpg',48,12),
(59,'Spring and summershoes','Comfortable stretch cloth\, lightweight body; \,rubber sole\, anti-skid wear;',20,9,4,137,'https://dummyjson.com/image/i/products/59/thumbnail.jpg',49,12),
(60,'Stylish Casual Jeans Shoes','High Quality \,Stylish design \,Comfortable wear \,FAshion \,Durable',58,8,5,129,'https://dummyjson.com/image/i/products/60/thumbnail.jpg',49,12),
(61,'Leather Straps Wristwatch','Style:Sport \,Clasp:Buckles \,Water Resistance Depth:3Bar',120,7,5,91,'https://dummyjson.com/image/i/products/61/thumbnail.jpg',51,13),
(62,'Waterproof Leather Brand Watch','Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours',46,3,4,95,'https://dummyjson.com/image/i/products/62/thumbnail.jpg',52,13),
(63,'Royal Blue Premium Watch','Men Silver Chain Royal Blue Premium Watch Latest Analog Watch',50,3,5,142,'https://dummyjson.com/image/i/products/63/thumbnail.webp',52,13),
(64,'Leather Strap Skeleton Watch','Leather Strap Skeleton Watch for Men - Stylish and Latest Design',46,10,5,61,'https://dummyjson.com/image/i/products/64/thumbnail.jpg',53,13),
(65,'Stainless Steel Wrist Watch','Stylish Watch For Man (Luxury) Classy Men''s Stainless Steel Wrist Watch - Box Packed',47,18,5,94,'https://dummyjson.com/image/i/products/65/thumbnail.webp',54,13),
(66,'Steel Analog Couple Watches','Elegant design\, Stylish \,Unique & Trendy\,Comfortable wear',35,3,5,24,'https://dummyjson.com/image/i/products/66/thumbnail.jpg',55,14),
(67,'Fashion Magnetic Wrist Watch','Buy this awesome  The product is originally manufactured by the company and it''s a top selling product with a very reasonable',60,17,4,46,'https://dummyjson.com/image/i/products/67/thumbnail.jpg',55,14),
(68,'Stylish Luxury Digital Watch','Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls',57,9,5,77,'https://dummyjson.com/image/i/products/68/thumbnail.webp',56,14),
(69,'Golden Watch Pearls Bracelet Watch','Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women',47,18,5,89,'https://dummyjson.com/image/i/products/69/thumbnail.jpg',57,14),
(70,'Stainless Steel Women','Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies',35,9,4,111,'https://dummyjson.com/image/i/products/70/thumbnail.jpg',58,14),
(71,'Women Shoulder Bags','LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies',46,15,5,17,'https://dummyjson.com/image/i/products/71/thumbnail.jpg',59,15),
(72,'Handbag For Girls','This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.',23,18,5,27,'https://dummyjson.com/image/i/products/72/thumbnail.webp',59,15),
(73,'Fancy hand clutch','This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.',44,10,4,101,'https://dummyjson.com/image/i/products/73/thumbnail.jpg',58,15),
(74,'Leather Hand Bag','It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys\, kids\, women\, girls and also for unisex.',57,11,4,43,'https://dummyjson.com/image/i/products/74/thumbnail.jpg',60,15),
(75,'Seven Pocket Women Bag','Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag',68,15,5,13,'https://dummyjson.com/image/i/products/75/thumbnail.jpg',61,15),
(76,'Silver Ring Set Women','Jewelry Type:RingsCertificate Type:NonePlating:Silver PlatedShapeattern:noneStyle:CLASSICReligious',70,14,5,51,'https://dummyjson.com/image/i/products/76/thumbnail.jpg',62,16),
(77,'Rose Ring','Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable',100,3,4,149,'https://dummyjson.com/image/i/products/77/thumbnail.jpg',60,16),
(78,'Rhinestone Korean Style Open Rings','Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women',30,8,5,9,'https://dummyjson.com/image/i/products/78/thumbnail.jpg',63,16),
(79,'Elegant Female Pearl Earrings','Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set',30,13,5,16,'https://dummyjson.com/image/i/products/79/thumbnail.jpg',63,16),
(80,'Chain Pin Tassel Earrings','Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)',45,18,5,9,'https://dummyjson.com/image/i/products/80/thumbnail.jpg',64,16),
(81,'Round Silver Frame Sun Glasses','A pair of sunglasses can protect your eyes from being hurt. For car driving\, vacation travel\, outdoor activities\, social gatherings\,',19,10,5,78,'https://dummyjson.com/image/i/products/81/thumbnail.jpg',65,17),
(82,'Kabir Singh Square Sunglass','Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass',50,16,5,78,'https://dummyjson.com/image/i/products/82/thumbnail.jpg',65,17),
(83,'Wiley X Night Vision Yellow Glasses','Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches',30,6,5,115,'https://dummyjson.com/image/i/products/83/thumbnail.jpg',66,17),
(84,'Square Sunglasses','Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059',28,14,5,64,'https://dummyjson.com/image/i/products/84/thumbnail.jpg',66,17),
(85,'LouisWill Men Sunglasses','LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers',50,11,5,92,'https://dummyjson.com/image/i/products/85/thumbnail.jpg',59,17),
(86,'Bluetooth Aux','Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3',25,11,5,22,'https://dummyjson.com/image/i/products/86/thumbnail.jpg',67,18),
(87,'t Temperature Controller Incubator Controller','Both Heat and Cool Purpose\, Temperature control range; -50 to +110\, Temperature measurement accuracy; 0.1\, Control accuracy; 0.1',40,11,5,37,'https://dummyjson.com/image/i/products/87/thumbnail.jpg',68,18),
(88,'TC Reusable Silicone Magic Washing Gloves','TC Reusable Silicone Magic Washing Gloves with Scrubber\, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen\, Dishes\, Vegetables and Fruits\, Bathroom\, Car Wash\, Pet Care and Multipurpose',29,3,5,42,'https://dummyjson.com/image/i/products/88/thumbnail.jpg',69,18),
(89,'Qualcomm original Car Charger','best Quality CHarger \, Highly Recommended to all best Quality CHarger \, Highly Recommended to all',40,18,4,79,'https://dummyjson.com/image/i/products/89/thumbnail.jpg',69,18),
(90,'Cycle Bike Glow','Universal fitment and easy to install no special wires\, can be easily installed and removed. Fits most standard tyre air stem valves of road\, mountain bicycles\, motocycles and cars.Bright led will turn on w',35,11,4,63,'https://dummyjson.com/image/i/products/90/thumbnail.jpg',70,18),
(91,'Black Motorbike','Engine Type:Wet sump\, Single Cylinder\, Four Stroke\, Two Valves\, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke:47.0 x 49.5 MM',569,14,4,115,'https://dummyjson.com/image/i/products/91/thumbnail.jpg',71,19),
(92,'HOT SALE IN EUROPE electric racing motorcycle','HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles',920,14,4,22,'https://dummyjson.com/image/i/products/92/thumbnail.jpg',72,19),
(93,'Automatic Motor Gas Motorcycles','150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter',1050,3,5,127,'https://dummyjson.com/image/i/products/93/thumbnail.jpg',73,19),
(94,'new arrivals Fashion motocross goggles','new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle',900,4,4,109,'https://dummyjson.com/image/i/products/94/thumbnail.webp',74,19),
(95,'Wholesale cargo lashing Belt','Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle',930,18,4,144,'https://dummyjson.com/image/i/products/95/thumbnail.jpg',75,19),
(96,'lighting ceiling kitchen','Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern',30,15,5,96,'https://dummyjson.com/image/i/products/96/thumbnail.jpg',76,20),
(97,'Metal Ceramic Flower','Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp',35,11,5,146,'https://dummyjson.com/image/i/products/97/thumbnail.jpg',77,20),
(98,'3 lights lndenpant kitchen islang','3 lights lndenpant kitchen islang dining room pendant rice paper chandelier contemporary led pendant light modern chandelier',34,6,5,44,'https://dummyjson.com/image/i/products/98/thumbnail.jpg',78,20),
(99,'American Vintage Wood Pendant Light','American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante',46,9,4,138,'https://dummyjson.com/image/i/products/99/thumbnail.jpg',77,20),
(100,'Crystal chandelier maria theresa for 12 light','Crystal chandelier maria theresa for 12 light',47,16,5,133,'https://dummyjson.com/image/i/products/100/thumbnail.jpg',79,20);

INSERT INTO images VALUES
(1,'https://dummyjson.com/image/i/products/1/1.jpg','https://dummyjson.com/image/i/products/1/2.jpg','https://dummyjson.com/image/i/products/1/3.jpg','https://dummyjson.com/image/i/products/1/4.jpg','https://dummyjson.com/image/i/products/1/thumbnail.jpg',NULL),
(2,'https://dummyjson.com/image/i/products/2/1.jpg','https://dummyjson.com/image/i/products/2/2.jpg','https://dummyjson.com/image/i/products/2/3.jpg','https://dummyjson.com/image/i/products/2/thumbnail.jpg',NULL,NULL),
(3,'https://dummyjson.com/image/i/products/3/1.jpg',NULL,NULL,NULL,NULL,NULL),
(4,'https://dummyjson.com/image/i/products/4/1.jpg','https://dummyjson.com/image/i/products/4/2.jpg','https://dummyjson.com/image/i/products/4/3.jpg','https://dummyjson.com/image/i/products/4/4.jpg','https://dummyjson.com/image/i/products/4/thumbnail.jpg',NULL),
(5,'https://dummyjson.com/image/i/products/5/1.jpg','https://dummyjson.com/image/i/products/5/2.jpg','https://dummyjson.com/image/i/products/5/3.jpg',NULL,NULL,NULL),
(6,'https://dummyjson.com/image/i/products/6/1.png','https://dummyjson.com/image/i/products/6/2.jpg','https://dummyjson.com/image/i/products/6/3.png','https://dummyjson.com/image/i/products/6/4.jpg',NULL,NULL),
(7,'https://dummyjson.com/image/i/products/7/1.jpg','https://dummyjson.com/image/i/products/7/2.jpg','https://dummyjson.com/image/i/products/7/3.jpg','https://dummyjson.com/image/i/products/7/thumbnail.jpg',NULL,NULL),
(8,'https://dummyjson.com/image/i/products/8/1.jpg','https://dummyjson.com/image/i/products/8/2.jpg','https://dummyjson.com/image/i/products/8/3.jpg','https://dummyjson.com/image/i/products/8/4.jpg','https://dummyjson.com/image/i/products/8/thumbnail.jpg',NULL),
(9,'https://dummyjson.com/image/i/products/9/1.jpg','https://dummyjson.com/image/i/products/9/2.png','https://dummyjson.com/image/i/products/9/3.png','https://dummyjson.com/image/i/products/9/4.jpg','https://dummyjson.com/image/i/products/9/thumbnail.jpg',NULL),
(10,'https://dummyjson.com/image/i/products/10/1.jpg','https://dummyjson.com/image/i/products/10/2.jpg','https://dummyjson.com/image/i/products/10/3.jpg','https://dummyjson.com/image/i/products/10/thumbnail.jpeg',NULL,NULL),
(11,'https://dummyjson.com/image/i/products/11/1.jpg','https://dummyjson.com/image/i/products/11/2.jpg','https://dummyjson.com/image/i/products/11/3.jpg','https://dummyjson.com/image/i/products/11/thumbnail.jpg',NULL,NULL),
(12,'https://dummyjson.com/image/i/products/12/1.jpg','https://dummyjson.com/image/i/products/12/2.jpg','https://dummyjson.com/image/i/products/12/3.png','https://dummyjson.com/image/i/products/12/4.jpg','https://dummyjson.com/image/i/products/12/thumbnail.jpg',NULL),
(13,'https://dummyjson.com/image/i/products/13/1.jpg','https://dummyjson.com/image/i/products/13/2.png','https://dummyjson.com/image/i/products/13/3.jpg','https://dummyjson.com/image/i/products/13/4.jpg','https://dummyjson.com/image/i/products/13/thumbnail.webp',NULL),
(14,'https://dummyjson.com/image/i/products/14/1.jpg','https://dummyjson.com/image/i/products/14/2.jpg','https://dummyjson.com/image/i/products/14/3.jpg','https://dummyjson.com/image/i/products/14/thumbnail.jpg',NULL,NULL),
(15,'https://dummyjson.com/image/i/products/15/1.jpg','https://dummyjson.com/image/i/products/15/2.jpg','https://dummyjson.com/image/i/products/15/3.jpg','https://dummyjson.com/image/i/products/15/4.jpg','https://dummyjson.com/image/i/products/15/thumbnail.jpg',NULL),
(16,'https://dummyjson.com/image/i/products/16/1.png','https://dummyjson.com/image/i/products/16/2.webp','https://dummyjson.com/image/i/products/16/3.jpg','https://dummyjson.com/image/i/products/16/4.jpg','https://dummyjson.com/image/i/products/16/thumbnail.jpg',NULL),
(17,'https://dummyjson.com/image/i/products/17/1.jpg','https://dummyjson.com/image/i/products/17/2.jpg','https://dummyjson.com/image/i/products/17/3.jpg','https://dummyjson.com/image/i/products/17/thumbnail.jpg',NULL,NULL),
(18,'https://dummyjson.com/image/i/products/18/1.jpg','https://dummyjson.com/image/i/products/18/2.jpg','https://dummyjson.com/image/i/products/18/3.jpg','https://dummyjson.com/image/i/products/18/4.jpg','https://dummyjson.com/image/i/products/18/thumbnail.jpg',NULL),
(19,'https://dummyjson.com/image/i/products/19/1.jpg','https://dummyjson.com/image/i/products/19/2.jpg','https://dummyjson.com/image/i/products/19/3.png','https://dummyjson.com/image/i/products/19/thumbnail.jpg',NULL,NULL),
(20,'https://dummyjson.com/image/i/products/20/1.jpg','https://dummyjson.com/image/i/products/20/2.jpg','https://dummyjson.com/image/i/products/20/3.jpg','https://dummyjson.com/image/i/products/20/4.jpg','https://dummyjson.com/image/i/products/20/thumbnail.jpg',NULL),
(21,'https://dummyjson.com/image/i/products/21/1.png','https://dummyjson.com/image/i/products/21/2.jpg','https://dummyjson.com/image/i/products/21/3.jpg',NULL,NULL,NULL),
(22,'https://dummyjson.com/image/i/products/22/1.jpg','https://dummyjson.com/image/i/products/22/2.jpg','https://dummyjson.com/image/i/products/22/3.jpg',NULL,NULL,NULL),
(23,'https://dummyjson.com/image/i/products/23/1.jpg','https://dummyjson.com/image/i/products/23/2.jpg','https://dummyjson.com/image/i/products/23/3.jpg','https://dummyjson.com/image/i/products/23/4.jpg','https://dummyjson.com/image/i/products/23/thumbnail.jpg',NULL),
(24,'https://dummyjson.com/image/i/products/24/1.jpg','https://dummyjson.com/image/i/products/24/2.jpg','https://dummyjson.com/image/i/products/24/3.jpg','https://dummyjson.com/image/i/products/24/4.jpg','https://dummyjson.com/image/i/products/24/thumbnail.jpg',NULL),
(25,'https://dummyjson.com/image/i/products/25/1.png','https://dummyjson.com/image/i/products/25/2.jpg','https://dummyjson.com/image/i/products/25/3.png','https://dummyjson.com/image/i/products/25/4.jpg','https://dummyjson.com/image/i/products/25/thumbnail.jpg',NULL),
(26,'https://dummyjson.com/image/i/products/26/1.jpg','https://dummyjson.com/image/i/products/26/2.jpg','https://dummyjson.com/image/i/products/26/3.jpg','https://dummyjson.com/image/i/products/26/4.jpg','https://dummyjson.com/image/i/products/26/5.jpg','https://dummyjson.com/image/i/products/26/thumbnail.jpg'),
(27,'https://dummyjson.com/image/i/products/27/1.jpg','https://dummyjson.com/image/i/products/27/2.jpg','https://dummyjson.com/image/i/products/27/3.jpg','https://dummyjson.com/image/i/products/27/4.jpg','https://dummyjson.com/image/i/products/27/thumbnail.webp',NULL),
(28,'https://dummyjson.com/image/i/products/28/1.jpg','https://dummyjson.com/image/i/products/28/2.jpg','https://dummyjson.com/image/i/products/28/3.png','https://dummyjson.com/image/i/products/28/4.jpg','https://dummyjson.com/image/i/products/28/thumbnail.jpg',NULL),
(29,'https://dummyjson.com/image/i/products/29/1.jpg','https://dummyjson.com/image/i/products/29/2.jpg','https://dummyjson.com/image/i/products/29/3.webp','https://dummyjson.com/image/i/products/29/4.webp','https://dummyjson.com/image/i/products/29/thumbnail.webp',NULL),
(30,'https://dummyjson.com/image/i/products/30/1.jpg','https://dummyjson.com/image/i/products/30/2.jpg','https://dummyjson.com/image/i/products/30/3.jpg','https://dummyjson.com/image/i/products/30/thumbnail.jpg',NULL,NULL),
(31,'https://dummyjson.com/image/i/products/31/1.jpg','https://dummyjson.com/image/i/products/31/2.jpg','https://dummyjson.com/image/i/products/31/3.jpg','https://dummyjson.com/image/i/products/31/4.jpg','https://dummyjson.com/image/i/products/31/thumbnail.jpg',NULL),
(32,'https://dummyjson.com/image/i/products/32/1.jpg','https://dummyjson.com/image/i/products/32/2.jpg','https://dummyjson.com/image/i/products/32/3.jpg','https://dummyjson.com/image/i/products/32/thumbnail.jpg',NULL,NULL),
(33,'https://dummyjson.com/image/i/products/33/1.jpg','https://dummyjson.com/image/i/products/33/2.jpg','https://dummyjson.com/image/i/products/33/3.jpg','https://dummyjson.com/image/i/products/33/4.jpg','https://dummyjson.com/image/i/products/33/thumbnail.jpg',NULL),
(34,'https://dummyjson.com/image/i/products/34/1.jpg','https://dummyjson.com/image/i/products/34/2.jpg','https://dummyjson.com/image/i/products/34/3.jpg','https://dummyjson.com/image/i/products/34/4.jpg','https://dummyjson.com/image/i/products/34/thumbnail.jpg',NULL),
(35,'https://dummyjson.com/image/i/products/35/1.jpg','https://dummyjson.com/image/i/products/35/2.jpg','https://dummyjson.com/image/i/products/35/3.jpg','https://dummyjson.com/image/i/products/35/4.jpg','https://dummyjson.com/image/i/products/35/thumbnail.jpg',NULL),
(36,'https://dummyjson.com/image/i/products/36/1.jpg','https://dummyjson.com/image/i/products/36/2.webp','https://dummyjson.com/image/i/products/36/3.webp','https://dummyjson.com/image/i/products/36/4.jpg','https://dummyjson.com/image/i/products/36/thumbnail.jpg',NULL),
(37,'https://dummyjson.com/image/i/products/37/1.jpg','https://dummyjson.com/image/i/products/37/2.jpg','https://dummyjson.com/image/i/products/37/3.jpg','https://dummyjson.com/image/i/products/37/4.jpg','https://dummyjson.com/image/i/products/37/thumbnail.jpg',NULL),
(38,'https://dummyjson.com/image/i/products/38/1.png','https://dummyjson.com/image/i/products/38/2.jpg','https://dummyjson.com/image/i/products/38/3.jpg','https://dummyjson.com/image/i/products/38/4.jpg',NULL,NULL),
(39,'https://dummyjson.com/image/i/products/39/1.jpg','https://dummyjson.com/image/i/products/39/2.jpg','https://dummyjson.com/image/i/products/39/3.jpg','https://dummyjson.com/image/i/products/39/4.jpg','https://dummyjson.com/image/i/products/39/thumbnail.jpg',NULL),
(40,'https://dummyjson.com/image/i/products/40/1.jpg','https://dummyjson.com/image/i/products/40/2.jpg',NULL,NULL,NULL,NULL),
(41,'https://dummyjson.com/image/i/products/41/1.jpg','https://dummyjson.com/image/i/products/41/2.webp','https://dummyjson.com/image/i/products/41/3.jpg','https://dummyjson.com/image/i/products/41/4.jpg','https://dummyjson.com/image/i/products/41/thumbnail.webp',NULL),
(42,'https://dummyjson.com/image/i/products/42/1.png','https://dummyjson.com/image/i/products/42/2.png','https://dummyjson.com/image/i/products/42/3.png','https://dummyjson.com/image/i/products/42/4.jpg','https://dummyjson.com/image/i/products/42/thumbnail.jpg',NULL),
(43,'https://dummyjson.com/image/i/products/43/1.jpg','https://dummyjson.com/image/i/products/43/2.jpg','https://dummyjson.com/image/i/products/43/3.jpg','https://dummyjson.com/image/i/products/43/4.jpg','https://dummyjson.com/image/i/products/43/thumbnail.jpg',NULL),
(44,'https://dummyjson.com/image/i/products/44/1.jpg','https://dummyjson.com/image/i/products/44/2.jpg','https://dummyjson.com/image/i/products/44/3.jpg','https://dummyjson.com/image/i/products/44/4.jpg','https://dummyjson.com/image/i/products/44/thumbnail.jpg',NULL),
(45,'https://dummyjson.com/image/i/products/45/1.jpg','https://dummyjson.com/image/i/products/45/2.webp','https://dummyjson.com/image/i/products/45/3.jpg','https://dummyjson.com/image/i/products/45/4.jpg','https://dummyjson.com/image/i/products/45/thumbnail.jpg',NULL),
(46,'https://dummyjson.com/image/i/products/46/1.webp','https://dummyjson.com/image/i/products/46/2.jpg','https://dummyjson.com/image/i/products/46/3.jpg','https://dummyjson.com/image/i/products/46/4.jpg','https://dummyjson.com/image/i/products/46/thumbnail.jpg',NULL),
(47,'https://dummyjson.com/image/i/products/47/1.jpg','https://dummyjson.com/image/i/products/47/2.jpg','https://dummyjson.com/image/i/products/47/3.jpg','https://dummyjson.com/image/i/products/47/thumbnail.jpeg',NULL,NULL),
(48,'https://dummyjson.com/image/i/products/48/1.jpg','https://dummyjson.com/image/i/products/48/2.jpg','https://dummyjson.com/image/i/products/48/3.jpg','https://dummyjson.com/image/i/products/48/4.jpg','https://dummyjson.com/image/i/products/48/thumbnail.jpg',NULL),
(49,'https://dummyjson.com/image/i/products/49/1.jpg','https://dummyjson.com/image/i/products/49/2.jpg','https://dummyjson.com/image/i/products/49/3.webp','https://dummyjson.com/image/i/products/49/thumbnail.jpg',NULL,NULL),
(50,'https://dummyjson.com/image/i/products/50/1.jpeg','https://dummyjson.com/image/i/products/50/2.jpg','https://dummyjson.com/image/i/products/50/3.jpg',NULL,NULL,NULL),
(51,'https://dummyjson.com/image/i/products/51/1.png','https://dummyjson.com/image/i/products/51/2.jpg','https://dummyjson.com/image/i/products/51/3.jpg','https://dummyjson.com/image/i/products/51/thumbnail.jpg',NULL,NULL),
(52,'https://dummyjson.com/image/i/products/52/1.png','https://dummyjson.com/image/i/products/52/2.png','https://dummyjson.com/image/i/products/52/3.jpg','https://dummyjson.com/image/i/products/52/4.jpg','https://dummyjson.com/image/i/products/52/thumbnail.jpg',NULL),
(53,'https://dummyjson.com/image/i/products/53/1.webp','https://dummyjson.com/image/i/products/53/2.jpg','https://dummyjson.com/image/i/products/53/3.jpg','https://dummyjson.com/image/i/products/53/4.jpg','https://dummyjson.com/image/i/products/53/thumbnail.jpg',NULL),
(54,'https://dummyjson.com/image/i/products/54/1.jpg','https://dummyjson.com/image/i/products/54/2.jpg','https://dummyjson.com/image/i/products/54/3.jpg','https://dummyjson.com/image/i/products/54/4.jpg','https://dummyjson.com/image/i/products/54/thumbnail.jpg',NULL),
(55,'https://dummyjson.com/image/i/products/55/1.jpg','https://dummyjson.com/image/i/products/55/2.webp','https://dummyjson.com/image/i/products/55/3.jpg','https://dummyjson.com/image/i/products/55/4.jpg','https://dummyjson.com/image/i/products/55/thumbnail.jpg',NULL),
(56,'https://dummyjson.com/image/i/products/56/1.jpg','https://dummyjson.com/image/i/products/56/2.jpg','https://dummyjson.com/image/i/products/56/3.jpg','https://dummyjson.com/image/i/products/56/4.jpg','https://dummyjson.com/image/i/products/56/5.jpg','https://dummyjson.com/image/i/products/56/thumbnail.jpg'),
(57,'https://dummyjson.com/image/i/products/57/1.jpg','https://dummyjson.com/image/i/products/57/2.jpg','https://dummyjson.com/image/i/products/57/3.jpg','https://dummyjson.com/image/i/products/57/4.jpg','https://dummyjson.com/image/i/products/57/thumbnail.jpg',NULL),
(58,'https://dummyjson.com/image/i/products/58/1.jpg','https://dummyjson.com/image/i/products/58/2.jpg','https://dummyjson.com/image/i/products/58/3.jpg','https://dummyjson.com/image/i/products/58/4.jpg','https://dummyjson.com/image/i/products/58/thumbnail.jpg',NULL),
(59,'https://dummyjson.com/image/i/products/59/1.jpg','https://dummyjson.com/image/i/products/59/2.jpg','https://dummyjson.com/image/i/products/59/3.jpg','https://dummyjson.com/image/i/products/59/4.jpg','https://dummyjson.com/image/i/products/59/thumbnail.jpg',NULL),
(60,'https://dummyjson.com/image/i/products/60/1.jpg','https://dummyjson.com/image/i/products/60/2.jpg','https://dummyjson.com/image/i/products/60/3.jpg','https://dummyjson.com/image/i/products/60/thumbnail.jpg',NULL,NULL),
(61,'https://dummyjson.com/image/i/products/61/1.jpg','https://dummyjson.com/image/i/products/61/2.png','https://dummyjson.com/image/i/products/61/3.jpg',NULL,NULL,NULL),
(62,'https://dummyjson.com/image/i/products/62/1.jpg','https://dummyjson.com/image/i/products/62/2.jpg',NULL,NULL,NULL,NULL),
(63,'https://dummyjson.com/image/i/products/63/1.jpg','https://dummyjson.com/image/i/products/63/2.jpg','https://dummyjson.com/image/i/products/63/3.png','https://dummyjson.com/image/i/products/63/4.jpeg',NULL,NULL),
(64,'https://dummyjson.com/image/i/products/64/1.jpg','https://dummyjson.com/image/i/products/64/2.webp','https://dummyjson.com/image/i/products/64/3.jpg','https://dummyjson.com/image/i/products/64/thumbnail.jpg',NULL,NULL),
(65,'https://dummyjson.com/image/i/products/65/1.jpg','https://dummyjson.com/image/i/products/65/2.webp','https://dummyjson.com/image/i/products/65/3.jpg','https://dummyjson.com/image/i/products/65/4.webp','https://dummyjson.com/image/i/products/65/thumbnail.webp',NULL),
(66,'https://dummyjson.com/image/i/products/66/1.jpg','https://dummyjson.com/image/i/products/66/2.jpg','https://dummyjson.com/image/i/products/66/3.jpg','https://dummyjson.com/image/i/products/66/4.JPG','https://dummyjson.com/image/i/products/66/thumbnail.jpg',NULL),
(67,'https://dummyjson.com/image/i/products/67/1.jpg','https://dummyjson.com/image/i/products/67/2.jpg','https://dummyjson.com/image/i/products/67/3.jpg','https://dummyjson.com/image/i/products/67/4.jpg','https://dummyjson.com/image/i/products/67/thumbnail.jpg',NULL),
(68,'https://dummyjson.com/image/i/products/68/1.jpg','https://dummyjson.com/image/i/products/68/2.jpg',NULL,NULL,NULL,NULL),
(69,'https://dummyjson.com/image/i/products/69/1.jpg','https://dummyjson.com/image/i/products/69/2.jpg','https://dummyjson.com/image/i/products/69/3.webp','https://dummyjson.com/image/i/products/69/4.jpg','https://dummyjson.com/image/i/products/69/thumbnail.jpg',NULL),
(70,'https://dummyjson.com/image/i/products/70/1.jpg','https://dummyjson.com/image/i/products/70/2.jpg','https://dummyjson.com/image/i/products/70/thumbnail.jpg',NULL,NULL,NULL),
(71,'https://dummyjson.com/image/i/products/71/1.jpg','https://dummyjson.com/image/i/products/71/2.jpg','https://dummyjson.com/image/i/products/71/3.webp','https://dummyjson.com/image/i/products/71/thumbnail.jpg',NULL,NULL),
(72,'https://dummyjson.com/image/i/products/72/1.jpg','https://dummyjson.com/image/i/products/72/2.png','https://dummyjson.com/image/i/products/72/3.webp','https://dummyjson.com/image/i/products/72/4.jpg','https://dummyjson.com/image/i/products/72/thumbnail.webp',NULL),
(73,'https://dummyjson.com/image/i/products/73/1.jpg','https://dummyjson.com/image/i/products/73/2.webp','https://dummyjson.com/image/i/products/73/3.jpg','https://dummyjson.com/image/i/products/73/thumbnail.jpg',NULL,NULL),
(74,'https://dummyjson.com/image/i/products/74/1.jpg','https://dummyjson.com/image/i/products/74/2.jpg','https://dummyjson.com/image/i/products/74/3.jpg','https://dummyjson.com/image/i/products/74/4.jpg','https://dummyjson.com/image/i/products/74/thumbnail.jpg',NULL),
(75,'https://dummyjson.com/image/i/products/75/1.jpg','https://dummyjson.com/image/i/products/75/2.jpg','https://dummyjson.com/image/i/products/75/3.jpg','https://dummyjson.com/image/i/products/75/thumbnail.jpg',NULL,NULL),
(76,'https://dummyjson.com/image/i/products/76/1.jpg','https://dummyjson.com/image/i/products/76/2.jpg','https://dummyjson.com/image/i/products/76/thumbnail.jpg',NULL,NULL,NULL),
(77,'https://dummyjson.com/image/i/products/77/1.jpg','https://dummyjson.com/image/i/products/77/2.jpg','https://dummyjson.com/image/i/products/77/3.jpg','https://dummyjson.com/image/i/products/77/thumbnail.jpg',NULL,NULL),
(78,'https://dummyjson.com/image/i/products/78/thumbnail.jpg',NULL,NULL,NULL,NULL,NULL),
(79,'https://dummyjson.com/image/i/products/79/1.jpg',NULL,NULL,NULL,NULL,NULL),
(80,'https://dummyjson.com/image/i/products/80/1.jpg','https://dummyjson.com/image/i/products/80/2.jpg','https://dummyjson.com/image/i/products/80/3.png','https://dummyjson.com/image/i/products/80/4.jpg','https://dummyjson.com/image/i/products/80/thumbnail.jpg',NULL),
(81,'https://dummyjson.com/image/i/products/81/1.jpg','https://dummyjson.com/image/i/products/81/2.jpg','https://dummyjson.com/image/i/products/81/3.jpg','https://dummyjson.com/image/i/products/81/4.webp','https://dummyjson.com/image/i/products/81/thumbnail.jpg',NULL),
(82,'https://dummyjson.com/image/i/products/82/1.jpg','https://dummyjson.com/image/i/products/82/2.webp','https://dummyjson.com/image/i/products/82/3.jpg','https://dummyjson.com/image/i/products/82/4.jpg','https://dummyjson.com/image/i/products/82/thumbnail.jpg',NULL),
(83,'https://dummyjson.com/image/i/products/83/1.jpg','https://dummyjson.com/image/i/products/83/2.jpg','https://dummyjson.com/image/i/products/83/3.jpg','https://dummyjson.com/image/i/products/83/4.jpg','https://dummyjson.com/image/i/products/83/thumbnail.jpg',NULL),
(84,'https://dummyjson.com/image/i/products/84/1.jpg','https://dummyjson.com/image/i/products/84/2.jpg','https://dummyjson.com/image/i/products/84/thumbnail.jpg',NULL,NULL,NULL),
(85,'https://dummyjson.com/image/i/products/85/1.jpg','https://dummyjson.com/image/i/products/85/2.jpg','https://dummyjson.com/image/i/products/85/thumbnail.jpg',NULL,NULL,NULL),
(86,'https://dummyjson.com/image/i/products/86/1.jpg','https://dummyjson.com/image/i/products/86/2.webp','https://dummyjson.com/image/i/products/86/3.jpg','https://dummyjson.com/image/i/products/86/4.jpg','https://dummyjson.com/image/i/products/86/thumbnail.jpg',NULL),
(87,'https://dummyjson.com/image/i/products/87/1.jpg','https://dummyjson.com/image/i/products/87/2.jpg','https://dummyjson.com/image/i/products/87/3.jpg','https://dummyjson.com/image/i/products/87/4.jpg','https://dummyjson.com/image/i/products/87/thumbnail.jpg',NULL),
(88,'https://dummyjson.com/image/i/products/88/1.jpg','https://dummyjson.com/image/i/products/88/2.jpg','https://dummyjson.com/image/i/products/88/3.jpg','https://dummyjson.com/image/i/products/88/4.webp','https://dummyjson.com/image/i/products/88/thumbnail.jpg',NULL),
(89,'https://dummyjson.com/image/i/products/89/1.jpg','https://dummyjson.com/image/i/products/89/2.jpg','https://dummyjson.com/image/i/products/89/3.jpg','https://dummyjson.com/image/i/products/89/4.jpg','https://dummyjson.com/image/i/products/89/thumbnail.jpg',NULL),
(90,'https://dummyjson.com/image/i/products/90/1.jpg','https://dummyjson.com/image/i/products/90/2.jpg','https://dummyjson.com/image/i/products/90/3.jpg','https://dummyjson.com/image/i/products/90/4.jpg','https://dummyjson.com/image/i/products/90/thumbnail.jpg',NULL),
(91,'https://dummyjson.com/image/i/products/91/1.jpg','https://dummyjson.com/image/i/products/91/2.jpg','https://dummyjson.com/image/i/products/91/3.jpg','https://dummyjson.com/image/i/products/91/4.jpg','https://dummyjson.com/image/i/products/91/thumbnail.jpg',NULL),
(92,'https://dummyjson.com/image/i/products/92/1.jpg','https://dummyjson.com/image/i/products/92/2.jpg','https://dummyjson.com/image/i/products/92/3.jpg','https://dummyjson.com/image/i/products/92/4.jpg',NULL,NULL),
(93,'https://dummyjson.com/image/i/products/93/1.jpg','https://dummyjson.com/image/i/products/93/2.jpg','https://dummyjson.com/image/i/products/93/3.jpg','https://dummyjson.com/image/i/products/93/4.jpg','https://dummyjson.com/image/i/products/93/thumbnail.jpg',NULL),
(94,'https://dummyjson.com/image/i/products/94/1.webp','https://dummyjson.com/image/i/products/94/2.jpg','https://dummyjson.com/image/i/products/94/3.jpg','https://dummyjson.com/image/i/products/94/thumbnail.webp',NULL,NULL),
(95,'https://dummyjson.com/image/i/products/95/1.jpg','https://dummyjson.com/image/i/products/95/2.jpg','https://dummyjson.com/image/i/products/95/3.jpg','https://dummyjson.com/image/i/products/95/4.jpg','https://dummyjson.com/image/i/products/95/thumbnail.jpg',NULL),
(96,'https://dummyjson.com/image/i/products/96/1.jpg','https://dummyjson.com/image/i/products/96/2.jpg','https://dummyjson.com/image/i/products/96/3.jpg','https://dummyjson.com/image/i/products/96/4.jpg','https://dummyjson.com/image/i/products/96/thumbnail.jpg',NULL),
(97,'https://dummyjson.com/image/i/products/97/1.jpg','https://dummyjson.com/image/i/products/97/2.jpg','https://dummyjson.com/image/i/products/97/3.jpg','https://dummyjson.com/image/i/products/97/4.webp','https://dummyjson.com/image/i/products/97/thumbnail.jpg',NULL),
(98,'https://dummyjson.com/image/i/products/98/1.jpg','https://dummyjson.com/image/i/products/98/2.jpg','https://dummyjson.com/image/i/products/98/3.jpg','https://dummyjson.com/image/i/products/98/4.jpg','https://dummyjson.com/image/i/products/98/thumbnail.jpg',NULL),
(99,'https://dummyjson.com/image/i/products/99/1.jpg','https://dummyjson.com/image/i/products/99/2.jpg','https://dummyjson.com/image/i/products/99/3.jpg','https://dummyjson.com/image/i/products/99/4.jpg','https://dummyjson.com/image/i/products/99/thumbnail.jpg',NULL),
(100,'https://dummyjson.com/image/i/products/100/1.jpg','https://dummyjson.com/image/i/products/100/2.jpg','https://dummyjson.com/image/i/products/100/3.jpg','https://dummyjson.com/image/i/products/100/thumbnail.jpg',NULL,NULL);